### ISSUE TITLE
pnpm install 时依赖安装错误 

### ISSUE THREAD

**Issue by johnsonwong666** [weimob-tech/titian-weapp#13]
<img width="947" alt="image" src="https://github.com/weimob-tech/titian-weapp/assets/64689255/6c836b80-8d36-4914-9da2-b3f37bd09403">
到npmjs上面搜索@titan/conditional-compilation 好像没有找到

**Comment by NiuZhuang** [comment]
是我们内部的一个包，给不小心带出来了。

现在删掉了。
