### ISSUE TITLE
样式覆盖 - 外部样式类ext-class不生效

### ISSUE THREAD

**Issue by Hinsco** [weimob-tech/titian-weapp#3]
**操作系统**: `MacOS Monterey`
**微信开发者工具**：`Stable 1.06.2301040`
**语言环境**：`TypeScript+less`
**问题组件**：`ti-row`、`ti-col`
**问题描述**：外部样式类`ext-class`不生效，无法修改内置的样式

- index.wxml
```html
<ti-row wx:for="{{list}}" ext-class="custom-row-class">
  <ti-col span="5">{{item.cur_price}}</ti-col>
  <ti-col span="5">{{item.buy_price}}</ti-col>
  <ti-col span="5">{{item.sell_price}}</ti-col>
</ti-row>
```

- index.less
```less
ti-row .custom-row-class {
  background-color: #fff;
}
```
- Wxml
<img width="598" alt="image" src="https://user-images.githubusercontent.com/110385016/216941882-c29cbbfb-7d93-4de5-aa83-16d585b21a3c.png">

- 结果： 颜色未修改？
<img width="420" alt="image" src="https://user-images.githubusercontent.com/110385016/216942642-a8d564b4-3b5d-43c2-95da-f2bf38602e03.png">

**Comment by robbe-luo** [comment]
fixed in 0.1.1
