### ISSUE TITLE
请问有不用每次重新构建npm的办法吗？

### ISSUE THREAD

**Issue by johnsonwong666** [weimob-tech/titian-weapp#7]
每次更新完代码，需要重新构建npm，新的内容才能生效

**Comment by NiuZhuang** [comment]
我理解一下你的操作：
1. 修改自己的源码
2. 使用小程序开发者工具，重新构建npm
3. 源码才能生效

是这样的吗？

**Comment by johnsonwong666** [comment]
> 我理解一下你的操作：
> 
> 1. 修改自己的源码
> 2. 使用小程序开发者工具，重新构建npm
> 3. 源码才能生效
> 
> 是这样的吗？

感谢回复。因为我是想调试一下组件库源码，可以看到 app.json里，usingComponents里面引用组件的路径是@titian-design/weapp/xxx，每一次修改源码的时候，打包输出的是路径是packages/weapp/esm，需要重新构建一次npm才能让我调整的代码加入到小程序自己的miniprogram_npm里，不知道是不是我操作有误。

**Comment by Suntgr** [comment]
@johnsonwong666 我把组件示例小程序里面使用组件npm包的方式去除了。你可以拉下代码再试试

**Comment by johnsonwong666** [comment]
> @johnsonwong666 我把组件示例小程序里面使用组件npm包的方式去除了。你可以拉下代码再试试

感谢
